# SPDX-FileCopyrightText: © 2024 Serhii “GooRoo” Olendarenko
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "*.lock"
SPDX-FileCopyrightText= "© 2024 Serhii “GooRoo” Olendarenko"
SPDX-License-Identifier= "CC0-1.0"
