# SPDX-FileCopyrightText: © 2025 Serhii “GooRoo” Olendarenko
# SPDX-FileContributor: Serhii Olendarenko <sergey.olendarenko@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause

name: 'Build: Run tests'

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.8"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        run: |
          uv run pytest --junit-xml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-results.xml
          retention-days: 30

      - name: Test Report
        uses: mikepenz/action-junit-report@d8d34855fefcfd2a15b5005b4cca125da5b41c8c
        with:
          report_paths: test-results.xml
