# SPDX-FileCopyrightText: © 2024 Serhii “GooRoo” Olendarenko
# SPDX-FileContributor: Serhii Olendarenko <sergey.olendarenko@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: 'Chore: REUSE Compliance'

on: [push, pull_request]

jobs:
  lint:
    name: reuse lint
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4
